# Generated by Django 5.2.7 on 2025-10-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('operationType', models.CharField(choices=[('BUY', '买入'), ('SELL', '卖出'), ('DV', '除权除息')], default='BUY', max_length=4)),
                ('price', models.FloatField(default=0)),
                ('count', models.IntegerField(blank=True, default=0)),
                ('fee', models.FloatField(default=0)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('cash', models.FloatField(default=0)),
                ('stock', models.FloatField(default=0)),
                ('reserve', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StockMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('isNew', models.BooleanField(default=False)),
                ('stockType', models.CharField(choices=[('SH60', '沪市'), ('SZ00', '深市'), ('SZ300', '创业板'), ('SH688', '科创板'), ('BJ', '北交所'), ('CONV', '可转债'), ('FUNDIN', '场内基金'), ('FUNDAB', '分级基金'), ('OTHER', '其它')], default='OTHER', max_length=6)),
            ],
        ),
    ]
