# Generated by Django 3.0.8 on 2020-07-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('operationType', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('count', models.IntegerField()),
                ('fee', models.FloatField(default=0)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
