# Generated by Django 3.0.8 on 2020-07-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('cash', models.FloatField()),
                ('stock', models.FloatField()),
                ('reserve', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='operation',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(),
        ),
    ]
