# Generated by Django 5.2.7 on 2025-11-13 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': '用户资金信息', 'verbose_name_plural': '用户资金信息'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': '股票操作记录', 'verbose_name_plural': '股票操作记录'},
        ),
        migrations.AlterModelOptions(
            name='stockmeta',
            options={'verbose_name': '股票元数据', 'verbose_name_plural': '股票元数据'},
        ),
        # 先重命名 key 字段为 info_type
        migrations.RenameField(
            model_name='info',
            old_name='key',
            new_name='info_type',
        ),
        # 添加 user 字段到 Operation
        migrations.AddField(
            model_name='operation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
            preserve_default=False,
        ),
        # 添加 user 字段到 Info
        migrations.AddField(
            model_name='info',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='infos', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
            preserve_default=False,
        ),
        # 修改 info_type 字段为枚举类型（在重命名之后）
        migrations.AlterField(
            model_name='info',
            name='info_type',
            field=models.CharField(choices=[('originCash', '本金'), ('incomeCash', '收益现金')], max_length=20, verbose_name='类型'),
        ),
        # 最后设置唯一约束（必须在 user 和 info_type 字段都存在之后）
        migrations.AlterUniqueTogether(
            name='info',
            unique_together={('user', 'info_type')},
        ),
        migrations.AlterField(
            model_name='info',
            name='value',
            field=models.CharField(blank=True, max_length=200, verbose_name='值'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='cash',
            field=models.FloatField(default=0, verbose_name='分红'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='code',
            field=models.CharField(max_length=200, verbose_name='股票代码'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='count',
            field=models.IntegerField(blank=True, default=0, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='fee',
            field=models.FloatField(default=0, verbose_name='手续费'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operationType',
            field=models.CharField(choices=[('BUY', '买入'), ('SELL', '卖出'), ('DV', '除权除息')], default='BUY', max_length=4, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='price',
            field=models.FloatField(default=0, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='reserve',
            field=models.FloatField(default=0, verbose_name='转增'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='stock',
            field=models.FloatField(default=0, verbose_name='送股'),
        ),
        migrations.AlterField(
            model_name='stockmeta',
            name='code',
            field=models.CharField(max_length=200, verbose_name='股票代码'),
        ),
        migrations.AlterField(
            model_name='stockmeta',
            name='isNew',
            field=models.BooleanField(default=False, verbose_name='是否新股'),
        ),
        migrations.AlterField(
            model_name='stockmeta',
            name='stockType',
            field=models.CharField(choices=[('SH60', '沪市'), ('SZ00', '深市'), ('SZ300', '创业板'), ('SH688', '科创板'), ('BJ', '北交所'), ('CONV', '可转债'), ('FUNDIN', '场内基金'), ('FUNDAB', '分级基金'), ('OTHER', '其它')], default='OTHER', max_length=6, verbose_name='股票类型'),
        ),
    ]
