# Generated by Django 3.0.8 on 2020-07-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200717_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
