# Generated by Django 5.2.7 on 2025-11-14 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_migrate_existing_data_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(verbose_name='交易时间')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='金额')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', '入金'), ('WITHDRAWAL', '出金')], max_length=20, verbose_name='交易类型')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='操作后余额')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '出入金记录',
                'verbose_name_plural': '出入金记录',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-transaction_date'], name='backend_cas_user_id_7284bb_idx'), models.Index(fields=['user', 'transaction_type'], name='backend_cas_user_id_dddb82_idx')],
            },
        ),
    ]
