# Generated by Django 5.2.7 on 2025-11-14 10:14

from django.db import migrations
from django.utils import timezone
from decimal import Decimal


def migrate_origin_cash_to_cashflow(apps, schema_editor):
    """
    将现有的 originCash 数据迁移到 CashFlow 表
    为每个用户创建一条初始入金记录（金额为正数）
    """
    Info = apps.get_model('backend', 'Info')
    CashFlow = apps.get_model('backend', 'CashFlow')
    
    # 获取所有 originCash 类型的 Info 记录
    origin_cash_infos = Info.objects.filter(info_type='originCash')
    
    for info in origin_cash_infos:
        try:
            amount = Decimal(info.value)
            if amount > 0:  # 只迁移大于0的本金
                CashFlow.objects.create(
                    user=info.user,
                    transaction_date=timezone.now(),
                    amount=amount
                )
        except (ValueError, TypeError):
            # 如果金额无法转换，跳过该记录
            pass


def reverse_migration(apps, schema_editor):
    """
    回滚迁移：删除所有迁移创建的 CashFlow 记录
    """
    CashFlow = apps.get_model('backend', 'CashFlow')
    # 删除所有记录（因为简化后没有comment字段来区分）
    CashFlow.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_add_cashflow_model'),
    ]

    operations = [
        migrations.RunPython(migrate_origin_cash_to_cashflow, reverse_migration),
    ]
