# Generated by Django 3.1.7 on 2021-04-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200717_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='operation',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operationType',
            field=models.CharField(choices=[('BUY', '买入'), ('SELL', '卖出'), ('DV', '除权除息')], default='BUY', max_length=4),
        ),
        migrations.AlterField(
            model_name='operation',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
