# Generated by Django 5.2.7 on 2025-11-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_migrate_origin_cash_to_cashflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflow',
            options={'ordering': ['-transaction_date'], 'verbose_name': '出入金记录', 'verbose_name_plural': '出入金记录'},
        ),
        migrations.RemoveIndex(
            model_name='cashflow',
            name='backend_cas_user_id_dddb82_idx',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='balance_after',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='transaction_type',
        ),
    ]
