# Generated by Django 5.2.7 on 2025-12-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_simplify_cashflow_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='transaction_date',
            field=models.DateField(verbose_name='交易日期'),
        ),
    ]
