# Generated by Django 6.0.3 on 2026-05-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_cashflow_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmeta',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='股票名称'),
        ),
    ]
