# Generated by Django 6.0.3 on 2026-06-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_operation_sortorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['date', 'sortOrder', 'id'], 'verbose_name': '股票操作记录', 'verbose_name_plural': '股票操作记录'},
        ),
        migrations.AlterField(
            model_name='stockmeta',
            name='stockType',
            field=models.CharField(choices=[('SH60', '沪市'), ('SZ00', '深市'), ('SZ300', '创业板'), ('SH688', '科创板'), ('BJ', '北交所'), ('CONV', '可转债'), ('FUNDIN', '场内基金'), ('FUNDAB', '分级基金'), ('HK', '港股通'), ('OTHER', '其它')], default='OTHER', max_length=6, verbose_name='股票类型'),
        ),
    ]
