# Generated by Django 6.0.3 on 2026-06-09 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_stockmeta_hk_stocktype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, verbose_name='股票代码')),
                ('risk', models.TextField(blank=True, default='', verbose_name='风险')),
                ('opportunity', models.TextField(blank=True, default='', verbose_name='机会')),
                ('leftPoint', models.FloatField(blank=True, null=True, verbose_name='左侧点')),
                ('trendPoint', models.FloatField(blank=True, null=True, verbose_name='趋势点')),
                ('bloodPoint', models.FloatField(blank=True, null=True, verbose_name='血筹点')),
                ('sortOrder', models.PositiveIntegerField(default=0, verbose_name='展示顺序')),
                ('comment', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_items', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '关注列表',
                'verbose_name_plural': '关注列表',
                'ordering': ['sortOrder', 'id'],
                'unique_together': {('user', 'code')},
            },
        ),
    ]
