# Generated by Django 6.0.3 on 2026-06-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_watchitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchitem',
            options={'ordering': ['id'], 'verbose_name': '关注股票列表', 'verbose_name_plural': '关注股票列表'},
        ),
        migrations.RemoveField(
            model_name='watchitem',
            name='sortOrder',
        ),
    ]
