# Generated by Django 6.0.3 on 2026-07-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_watchitem_sortorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchitem',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='是否隐藏'),
        ),
    ]
