# Generated by Django 6.0.3 on 2026-07-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_operation_watchitem_stock_meta_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='amount',
            field=models.FloatField(blank=True, default=None, help_text='仅港股通买卖填写；非港股留空', null=True, verbose_name='成交金额(人民币)'),
        ),
    ]
