# Generated by Django 6.0.3 on 2026-08-03 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_operation_amount_cny'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='amount',
            field=models.FloatField(blank=True, help_text='仅港股通买卖填写；非港股留空', null=True, verbose_name='成交金额(人民币)'),
        ),
        migrations.CreateModel(
            name='StockDailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, verbose_name='股票代码')),
                ('date', models.DateField(verbose_name='交易日期')),
                ('close', models.FloatField(verbose_name='收盘价')),
            ],
            options={
                'verbose_name': '日频收盘价',
                'verbose_name_plural': '日频收盘价',
                'ordering': ['code', 'date'],
                'indexes': [models.Index(fields=['code', 'date'], name='backend_sto_code_bb8c6e_idx')],
                'constraints': [models.UniqueConstraint(fields=('code', 'date'), name='uniq_stock_daily_price_code_date')],
            },
        ),
        migrations.CreateModel(
            name='PortfolioNavDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='交易日期')),
                ('nav', models.FloatField(verbose_name='净值')),
                ('units', models.FloatField(default=0, verbose_name='份额')),
                ('asset', models.FloatField(default=0, verbose_name='总资产')),
                ('cash', models.FloatField(default=0, verbose_name='现金')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_nav_dailies', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '组合日净值',
                'verbose_name_plural': '组合日净值',
                'ordering': ['user', 'date'],
                'indexes': [models.Index(fields=['user', 'date'], name='backend_por_user_id_65acb2_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uniq_portfolio_nav_user_date')],
            },
        ),
    ]
