# Generated by Django 6.0.3 on 2026-08-21 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_hkdcnydailyrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('sw_l1', '申万一级行业')], default='sw_l1', max_length=16, verbose_name='分类')),
                ('code', models.CharField(max_length=16, verbose_name='标签代码')),
                ('name', models.CharField(max_length=64, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'constraints': [models.UniqueConstraint(fields=('category', 'code'), name='uniq_tag_category_code')],
            },
        ),
        migrations.AddField(
            model_name='stockmeta',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='backend.tag', verbose_name='标签'),
        ),
    ]
