"""
Django settings for stockManager project.

Generated by 'django-admin startproject' using Django 3.0.8.
Updated for Django 5.2.7

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# 加载环境变量文件（与 settings.py 同目录）
DOTENV_PATH = Path(__file__).resolve().parent / '.env'
if DOTENV_PATH.exists():
    load_dotenv(DOTENV_PATH)

from . import __version__

# 使用 Path 替代 os.path（Django 3.1+ 推荐）
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CURRENT_DIR = Path(__file__).resolve().parent

VERSION = __version__

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# genAI_main_start
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG') == 'true'

ALLOWED_HOSTS =  ['*']

# Django 4.0+ 必需的 CSRF_TRUSTED_ORIGINS 配置 
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://127.0.0.1:8001',
    'http://localhost:8000',
    'http://localhost:8001',
]

# Django 3.2+ 必需的 DEFAULT_AUTO_FIELD 配置 
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Application definition

INSTALLED_APPS = [
    'backend.apps.BackendConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'werkzeug_debugger_runserver',
    'django_extensions',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 必须在 CommonMiddleware 之前
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ==================== CORS 跨域配置 ====================
# 使用 django-cors-headers 处理跨域请求

# 允许跨域请求携带凭证（Cookie、Session、CSRF Token）
CORS_ALLOW_CREDENTIALS = True

# 开发环境：允许所有域名（方便调试）
# 生产环境：应该注释掉这一行，只使用 CORS_ALLOWED_ORIGINS
CORS_ALLOW_ALL_ORIGINS = DEBUG  # 只在 DEBUG=True 时允许所有域名

# 允许的域名白名单（生产环境使用）
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://127.0.0.1:8001",
    "http://localhost:8000",
    "http://localhost:8001",
    # 生产环境添加你的域名：
    # "https://yourdomain.com",
    # "https://www.yourdomain.com",
]

# 允许的 HTTP 方法
CORS_ALLOW_METHODS = [
    'DELETE',   # 删除操作
    'GET',      # 查询操作
    'OPTIONS',  # 预检请求（必需）
    'PATCH',    # 部分更新
    'POST',     # 创建操作
    'PUT',      # 完整更新
]

# 允许的请求头
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',      # 认证信息
    'content-type',       # 内容类型（必需）
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',        # CSRF Token（必需）
    'x-requested-with',
]

ROOT_URLCONF = 'stockManager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'front' / 'dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stockManager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ==================== Redis 缓存配置 ====================
# Redis 缓存配置
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            # 注意：redis-py 5.0+ 中 HiredisParser 已移除，使用默认解析器即可
            # 'PARSER_CLASS': 'redis.connection.HiredisParser',  
            'PICKLE_VERSION': -1,  # 使用最新的 pickle 协议
            'SOCKET_CONNECT_TIMEOUT': 5,  # 连接超时
            'SOCKET_TIMEOUT': 5,  # 读写超时
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            # 序列化配置
            'SERIALIZER': 'django_redis.serializers.json.JSONSerializer',
        },
        'KEY_PREFIX': 'stockmanager',  # 键前缀，避免冲突
        'VERSION': 1,
    }
}



# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# 收集所有静态文件到这个目录（运行 collectstatic 后）
STATIC_ROOT = BASE_DIR / "staticfiles"

# 开发环境：额外的静态文件目录（Django 会自动从这里查找）
STATICFILES_DIRS = [
    BASE_DIR / "front" / "dist",
]

# Django 4.2+ 推荐使用 STORAGES 配置（替代废弃的 STATICFILES_STORAGE）
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# 日志配置
# 生产环境：使用 /var/log/stockmanager/django/
# 开发环境：使用项目目录下的 log（如果目录不存在会自动创建）
if os.path.exists('/var/log/stockmanager/django'):
    BASE_LOG_DIR = Path('/var/log/stockmanager/django')
else:
    BASE_LOG_DIR = CURRENT_DIR / "log"

if not BASE_LOG_DIR.exists():
    BASE_LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    # 日志格式
    'formatters': {
        'standard': {
            'format': '[%(asctime)s][%(threadName)s:%(thread)d][task_id:%(name)s][%(filename)s:%(lineno)d]'
                      '[%(levelname)s][%(message)s]'
        },
        'simple': {
            'format': '[%(levelname)s][%(asctime)s][%(filename)s:%(lineno)d]%(message)s'
        } 
    },
    # 过滤器
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    # 处理器
    'handlers': {
        # 终端输出
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        # 所有日志（按天自动轮转）
        'default': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': str(BASE_LOG_DIR / 'all.log'),
            'when': 'midnight',  # 每天午夜轮转
            'interval': 1,  # 每1天
            'backupCount': 30,  # 保留30天
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
        # 错误日志（按天自动轮转）
        'error': {
            'level': 'ERROR',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': str(BASE_LOG_DIR / 'error.log'),
            'when': 'midnight',
            'interval': 1,
            'backupCount': 90,  # 错误日志保留90天
            'formatter': 'standard',
            'encoding': 'utf-8',
        }
    },
    'loggers': {
        '': {
            'handlers': ['default', 'console', 'error'],
            'level': 'DEBUG',
            'propagate': True,
        }
    }
}